W7D2/music_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:create, :new, :show]
  resource :session, only:[:create, :destroy, :new]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy]
end

W7D2/music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  band_id    :integer          not null
#  studio     :boolean          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Album < ApplicationRecord
    validates :title, presence: true
    validates :title, presence: true
    validates :year, presence: true
    validates :title, uniqueness: {scope: :band_id}
    validates :studio, inclusion: {in: [true, false]}

    belongs_to :band

end

W7D2/music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

W7D2/music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Band < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_many :albums,
        dependent: :destroy,
        inverse_of: :band
end

W7D2/music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord

    before_validation :ensure_session_token

    validates :email, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: {minimum: 6}, allow_nil: true

    attr_reader :password

    def self.find_by_credentials(email, password)
        @user = User.find_by(email: email)
        if @user && @user.is_password?(password)
            @user
        else
            nil
        end
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(password)
        password_obj = BCrypt::Password.new(self.password_digest)
        password_obj.is_password?(password)
    end

    def generate_unique_session_token
        SecureRandom.urlsafe_base64
    end

    def reset_session_token!
        self.session_token = generate_unique_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= generate_unique_session_token
    end
end

W7D2/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :set_album, only: [:show, :edit, :update, :destroy]
    def set_album
        @album = Album.find_by(id: params[:id])
    end

    def new
        @band_id = params[:band_id]
        @album = Album.new
        render :new
    end

    def show
        render :show
    end

    def create
        @album = Album.new(album_params)
        # debugger
        if @album.save!
            redirect_to band_url(@album.band_id)
        else
            render :new
        end
    end

    def edit
        render :edit
    end

    def update
        if @album.update(album_params)
            redirect_to album_url(@album)
        else
            render :edit
        end

    end

    def destroy
        band = @album.band_id
        @album.destroy
        redirect_to band_url(band)
    end

    private
    def album_params
        params.require(:album).permit(:title, :year, :band_id, :studio)
    end
end

W7D2/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :login!, :logout!, :logged_in?
    #CRLLL
    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logged_in?
        !!current_user
    end

    def logout!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end
end

W7D2/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    before_action :set_band, only: [:show, :edit, :update, :destroy]

    def set_band
        @band = Band.find_by(id: params[:id])
    end

    def index
        @bands = Band.all
        render :index
    end

    def show
        render :show
    end

    def new
        @band = Band.new
        render :new
    end

    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to band_url(@band)
        else
            render :new
        end
    end

    def edit
        render :edit
    end

    def update
        if @band.update(band_params)
            redirect_to band_url(@band)
        else
            render :edit
        end
    end

    def destroy
        @band.destroy
        redirect_to bands_url
    end


    private
    def band_params
        params.require(:band).permit(:name)
    end
end

W7D2/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @User = User.new
        render :log_in
    end

    def create
        @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if @user 
            login!(@user)
            redirect_to user_url(@user)
        else
            render :log_in
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end

end

W7D2/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    def new
        @user = User.new
        render :sign_up
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            render :sign_up
        end


    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end

end

W7D2/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

W7D2/music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

W7D2/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W7D2/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W7D2/music_app/app/helpers/users_helper.rb
module UsersHelper
end

W7D2/music_app/app/views/albums/_album.html.erb
<h2>Album Name:</h2>
<p><%= album.title %></p>

<% if action == "index" %>
    <a href="<%= album_url(album) %>">Album Page</a> 
<% elsif action == "show" %>
    <a href="<%= edit_album_url(album) %>">Edit Album</a>
    <form action="<%= band_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" value="Delete Album">
      </form>
<% end %>

W7D2/music_app/app/views/albums/_form.html.erb
<% if action == "new" %>
    <% action_url = albums_url %>
    <% title = "New Album" %>
<% elsif action == "edit" %>
    <% action_url = album_url(@album)%>
    <% title = "Edit Album" %>
<% end %>

<h1><%= title %>:</h1>
<form action="<%= action_url %>" method="post">
    <% if action == "edit"%>
        <input type="hidden" name="_method" value="patch">
    <%end%>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
    <label>Title:
    <input type="text" name="album[title]" id="album_title" value="<%= @album.title %>">
    </label>
    <br>
    <br>
    <label>Year:
    <input type="text" name="album[year]" id="album_year" value="<%= @album.year %>">
    </label>
    <br>
    <br>
    <label >Studio:
    <label for="">True:
    <input type="radio" name="album[studio]" value="true">
    </label>
    <label for="">False:
    <input type="radio" name="album[studio]" value="false" >
    </label>
    </label>
    <br>
    <br>
    <% if action == "new" %>
    <input type="hidden" name="album[band_id]" value="<%= band_id %>">
    <% end %>
    <input type="submit" value="Submit">
</form>

W7D2/music_app/app/views/albums/edit.html.erb
<%= render "form", album: @album, action: "edit" %>

W7D2/music_app/app/views/albums/new.html.erb
<%= render 'form', album: @album, band_id: @band_id, action: 'new' %>

W7D2/music_app/app/views/albums/show.html.erb
<%= render "album", album: @album, action: "show"%>

W7D2/music_app/app/views/bands/_band.html.erb
<h3>Band Name:</h2>
<p><%= band.name %></p>


<% if action == "index" %>
    <a href="<%= band_url(band) %>">Band Page</a> 

<% elsif action == "show" %>
    <h3>Albums:</h3>
    <% band.albums.each do |album|%>
        <a href=" <%= album_url(album.id) %>"><%= album.title %></a>
        <br>
    <% end %>
    <br>

    <a href="<%= edit_band_url(band) %>">Edit Band</a>
    <br>

    <a href="<%= new_band_album_url(band) %>">New Album</a>
    <form action="<%= band_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" value="Delete Band">
      </form>
<% end %>

W7D2/music_app/app/views/bands/_form.html.erb
<% if action == "new" %>
    <% action_url = bands_url %>
    <% title = "New Band" %>
<% elsif action == "edit" %>
    <% action_url = band_url(@band)%>
    <% title = "Edit Band" %>
<% end %>

<h1><%= title %></h1>
<form action="<%= action_url %>" method="post">
    <% if action == "edit"%>
        <input type="hidden" name="_method" value="patch">
    <%end%>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
    <label for="new_name">Name:</label>
    <input type="text" name="band[name]" id="new_name" value="<%= @band.name %>">
    <br>
    <br>
    <input type="submit" value="Submit">
</form>

W7D2/music_app/app/views/bands/edit.html.erb
<%= render "form", band: @band, action: "edit" %>

W7D2/music_app/app/views/bands/index.html.erb
<h1>All Bands</h1>

<%@bands.each do |band|%>
    <%= render 'band', band: band, action: 'index' %>
<%end%>

W7D2/music_app/app/views/bands/new.html.erb
<%= render "form", band: @band, action: 'new' %>

W7D2/music_app/app/views/bands/show.html.erb
<%= render 'band', band: @band, action: 'show' %>

W7D2/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <header>
    <h1>Music App</h1>
    <% if logged_in? %>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" value="Log Out">
      </form>
    <% else %>
      <a href=" <%= new_user_url  %> ">Sign Up</a>
      <a href=" <%= new_session_url  %> ">Log In</a>
    <% end %>
    <a href="<%= new_band_url %>">New Band</a>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

W7D2/music_app/app/views/users/show.html.erb
<h1>User</h1>
<p><%= @user.email %></p>

W7D2/music_app/app/views/users/sign_up.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="su_email">Email:</label>
    <input type="email" name="user[email]" id="su_email" value="<%= @user.email %>">
    <br>
    <br>
    <label for="su_password">Password:</label>
    <input type="password" name="user[password]" id="su_password">
    <br>
    <br>
    <input type="submit" value="Sign Up">
</form>